### ISSUE TITLE
Why you create new TData ?

### ISSUE THREAD

**Issue by ElleNearMello** [gianlo/Akka.FSM.Examples#1]
In your C# code, TData is the object Coins.
When you are in a state and receive a message, you can alter this state (example: adding a Coin, so that Coins.Total is incremented). BUT in your code you "return new", so basically you don't alter the state, you create every time a new updated state.
Why so?
You should just alter the internal state of the FSM, not recreate a new updated one.

**Comment by gianlo** [comment]
At that level, the state is represented by the immutable Coins object. 
I prefer to have an immutable object to represent the current state, hence the new.
The state does mutate in the actor by getting a new Coins object when transitions happen.
Having immutable objects representing state does not contradict the actor mutating its internal state.
